name: build-docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_push:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bcmslab/linpsapp
          dockerfile: Dockerfile
          tags: latest
